services:
    backend:
        build: ./backend
        container_name: backend-healthbestie
        ports:
          - 3000:3000
    frontend:
        build: ./frontend
        container_name: frontend_healthbestie
        ports:
         - 3001:3001
        depends_on:
         - backend

    
